// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQbxLI0d-7BYvsEZGyHdFHhQ7QpjZMKE4',
    appId: '1:533250368394:web:d9a9745b400a8ac2085e73',
    messagingSenderId: '533250368394',
    projectId: 'dr-ahmed-clinic-d6e86',
    authDomain: 'dr-ahmed-clinic-d6e86.firebaseapp.com',
    storageBucket: 'dr-ahmed-clinic-d6e86.appspot.com',
    measurementId: 'G-D98VXRJ60Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXkG8DCsAm6f43zyRvJcGorjYCrkp4YuM',
    appId: '1:533250368394:android:0a8ff4f5af83f4c2085e73',
    messagingSenderId: '533250368394',
    projectId: 'dr-ahmed-clinic-d6e86',
    storageBucket: 'dr-ahmed-clinic-d6e86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQvt6mB2bq6OEsQICQP0mu6X6c2cwgZI',
    appId: '1:533250368394:ios:f8f16e388c5c54da085e73',
    messagingSenderId: '533250368394',
    projectId: 'dr-ahmed-clinic-d6e86',
    storageBucket: 'dr-ahmed-clinic-d6e86.appspot.com',
    iosBundleId: 'com.example.drAhmedClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQvt6mB2bq6OEsQICQP0mu6X6c2cwgZI',
    appId: '1:533250368394:ios:f8f16e388c5c54da085e73',
    messagingSenderId: '533250368394',
    projectId: 'dr-ahmed-clinic-d6e86',
    storageBucket: 'dr-ahmed-clinic-d6e86.appspot.com',
    iosBundleId: 'com.example.drAhmedClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQbxLI0d-7BYvsEZGyHdFHhQ7QpjZMKE4',
    appId: '1:533250368394:web:b39201f1e0526b46085e73',
    messagingSenderId: '533250368394',
    projectId: 'dr-ahmed-clinic-d6e86',
    authDomain: 'dr-ahmed-clinic-d6e86.firebaseapp.com',
    storageBucket: 'dr-ahmed-clinic-d6e86.appspot.com',
    measurementId: 'G-DGHS97CMF1',
  );
}
